import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  { 
    _id: uuid(),
    name: "Nike Air Max 90",
    brand: "Nike",
    image: "https://images.vegnonveg.com/resized/400X328/9403/nike-dunk-hi-retro-se-monarchmonarch-sail-6454f1639a713.jpg",
    original_price: 199,
    discounted_price: 159,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.6,
    reviews: 235,
    description:
      "Experience ultimate comfort and style with the iconic Nike Air Max 90 sneakers. Featuring a timeless design and enhanced cushioning for all-day wear.",
    size: 8,
  },
  {
    _id: uuid(),
    name: "Nike Zoom Pegasus 38",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/9276/air-penny-ii-whitephoton-dust-black-sail-6433a9de51688.jpg",
    original_price: 129,
    discounted_price: 109,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.8,
    reviews: 182,
    description:
      "Take your running to the next level with the Nike Zoom Pegasus 38. These lightweight and responsive shoes provide a smooth ride and optimal support.",
  },
  {
    _id: uuid(),
    name: "Nike React Infinity Run Flyknit",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/9268/air-force-1-07-lo-whitegame-royal-white-6432285ed1b00.jpg",
    original_price: 179,
    discounted_price: 149,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.7,
    reviews: 209,
    description:
      "Experience endless comfort and energy return with the Nike React Infinity Run Flyknit. These running shoes feature a supportive design to help reduce injuries.",
  },
  {
    _id: uuid(),
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/9160/air-force-1-07-lv8-summit-whitegame-royal-neutral-grey-6419a43e81b5a.jpg",
    original_price: 119,
    discounted_price: 89,
    category_name: "Running",
    is_stock: true,
    rating: 4.5,
    reviews: 301,
    description:
      "Step up your street style game with the iconic Nike Air Force 1 '07 sneakers. These classic kicks offer unbeatable comfort and a timeless look.",
  },
  {
    _id: uuid(),
    name: "Nike Revolution 5",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/9148/w-nike-dunk-low-lx-celestial-goldwheat-gold-sail-641463a10cbec.jpg",
    original_price: 79,
    discounted_price: 59,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.2,
    reviews: 132,
    description:
      "Achieve your fitness goals with the Nike Revolution 5. These versatile trainers provide excellent cushioning and support for all your workouts.",
  },
  {
    _id: uuid(),
    name: "Nike Joyride Run Flyknit",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/6/817419-100_1.jpg",
    original_price: 199,
    discounted_price: 169,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.4,
    reviews: 156,
    description:
      "Experience a new level of cushioning and responsiveness with the Nike Joyride Run Flyknit. These innovative running shoes make every step enjoyable.",
  },
  {
    _id: uuid(),
    name: "Nike SB Check Solarsoft",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/9358/w-nike-air-max-1-prm-ess-summit-whitesanddrift-phantom-644f4c41539c0.jpg",
    original_price: 69,
    discounted_price: 49,
    category_name: "Running",
    is_stock: true,
    rating: 4.1,
    reviews: 94,
    description:
      "Skate in style with the Nike SB Check Solarsoft shoes. These durable sneakers offer excellent boardfeel and comfort for your skateboarding sessions.",
  },
  {
    _id: uuid(),
    name: "Nike Court Vision Low",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/7883/air-force-1-low-retro-university-bluewhite-metallic-gold-6360b0c422e1d.jpg",
    original_price: 89,
    discounted_price: 69,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.3,
    reviews: 118,
    description:
      "Add a retro touch to your outfit with the Nike Court Vision Low. These classic-inspired sneakers provide a comfortable fit and timeless style.",
  },
  {
    _id: uuid(),
    name: "Nike Flex Experience RN 10",
    brand: "Nike",
    image:"https://images.vegnonveg.com/resized/400X328/9050/air-more-uptempo-96-coconut-milkteam-gold-team-gold-64056df2070df.jpg",
    original_price: 89,
    discounted_price: 69,
    category_name: "Running",
    is_stock: true,
    rating: 4.2,
    reviews: 118,
    description:
      "Add a retro touch to your outfit with the Nike Court Vision Low. These classic-inspired sneakers provide a comfortable fit and timeless style.",
  },

  {
    _id: uuid(),
    name: "Ultraboost 22",
    brand: "Addidas",
    image:"https://images.vegnonveg.com/resized/400X328/8965/ultraboost-23-ftwr-whitecore-blacksolar-red-63f60a21a6edb.jpg",
    original_price: 180,
    discounted_price: 144,
    category_name: "Running",
    is_stock: true,
    rating: 4.5,
    reviews: 1234,
    description:
      "These running shoes are designed to provide a comfortable and supportive ride.",

    size: 8,
  },
  {
    _id: uuid(),
    name: "Adizero Adios Pro 3",
    brand: "Addidas",
    image: "https://images.vegnonveg.com/resized/400X328/6656/dame-8-nonenonenone-625416ab0d907.jpg",
    original_price: 200,
    discounted_price: 160,
    category_name: "Running",
    is_stock: true,
    rating: 4.7,
    reviews: 897,
    description:
      "These running shoes are designed to help you achieve your personal best.",
    trending: true,
    size: 9,
  },
  {
    _id: uuid(),
    name: "Stan Smith",
    brand: "Addidas",
    image:"https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/9ca64392f1fc4a8ea060aed80116e79a_9366/stan-smith-shoes.jpg",
    original_price: 100,
    discounted_price: 75,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.3,
    reviews: 567,
    description: "These classic sneakers are a must-have for any wardrobe.",

    size: 7,
  },
  {
    _id: uuid(),
    name: "Superstar",
    brand: "Addidas",
    image:"https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/ff0654f4089f4413baa7aae700d2a08c_9366/superstar-shoes.jpg",
    original_price: 100,
    discounted_price: 75,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.4,
    reviews: 654,
    description: "These iconic sneakers are perfect for everyday wear.",

    size: 8,
  },
  {
    _id: uuid(),
    name: "Samba",
    brand: "Addidas",
    image:"https://images.vegnonveg.com/resized/400X328/8803/ultraboost-22-w-core-blackcore-blacklucid-blue-63bfebf4a9c15.jpg",
    original_price: 80,
    discounted_price: 60,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.2,
    reviews: 456,
    description: "These versatile sneakers can be dressed up or down.",

    size: 7,
  },
  {
    _id: uuid(),
    name: "Nizza",
    brand: "Addidas",
    image:"https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/0bc6e8957eda4686a226af8900d28fec_9366/adidas-nizza-x-moomin-platform-mid-shoes.jpg",
    original_price: 60,
    discounted_price: 45,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.1,
    reviews: 345,
    description:
      "These affordable sneakers are a great option for everyday wear.",

    size: 6,
  },
  {
    _id: uuid(),
    name: "Gazelle",
    brand: "Addidas",
    image:"https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/412a8543b99d49a2aa5aaef900d32ef7_9366/gazelle-shoes.jpg",
    original_price: 70,
    discounted_price: 55,
    category_name: "Lifestyle",
    is_stock: true,
    rating: 4.2,
    reviews: 432,
    description: "These classic sneakers are a great option for any occasion.",

    size: 7,
  },
  {
    _id: uuid(),
    name: "Campus",
    brand: "Vans",
    image:"https://images.vegnonveg.com/resized/400X328/6750/ua-authentic-mustard-goldtrue-white-63c921bc56d08.jpg",
    original_price: 60,
    discounted_price: 45,
    category_name: "Skateboarding",
    is_stock: true,
    rating: 4.0,
    reviews: 312,
    description: "These simple sneakers are a great option for everyday wear.",

    size: 6,
  },
    {
      _id: uuid(),
      name: "Old Skool",
      brand: "Vans",
      image:"https://images.vegnonveg.com/resized/400X328/6745/ua-old-skool-ravenfreesia-63c9200cdc0c4.jpg",
      original_price: 65,
      discounted_price: 55,
      category_name: "Skateboarding",
      is_stock: true,
      rating: 4.5,
      reviews: 987,
      description: "These classic Vans sneakers are a timeless choice for casual wear.",
      size: 9
    },
    {
      _id: uuid(),
      name: "Authentic",
      brand: "Vans",
      image:"https://images.vegnonveg.com/resized/400X328/6747/ua-sk8-hi-blacktrue-white-63c920bac2c7d.jpg",
      original_price: 50,
      discounted_price: 40,
      category_name: "Skateboarding",
      is_stock: true,
      rating: 4.3,
      reviews: 654,
      description: "The Vans Authentic is a versatile and comfortable sneaker suitable for any occasion.",
      size: 8
    },
    {
      _id: uuid(),

      name: "Sk8-Hi",
      brand: "Vans",
      image:"https://images.vegnonveg.com/resized/400X328/6735/mn-skate-sk8-hi-blue-6364eafcd51c2.jpg",
      original_price: 70,
      discounted_price: 60,
      category_name: "Skateboarding",
      is_stock: true,
      rating: 4.7,
      reviews: 876,
      description: "The Vans Sk8-Hi is a high-top sneaker that combines style and durability.",
      size: 10
    },
    {
      _id: uuid(),

      name: "Slip-On",
      brand: "Vans",
      image:"https://images.vegnonveg.com/resized/400X328/6733/mn-skate-slip-on-multi-63c8edb581f26.jpg",
      original_price: 55,
      discounted_price: 45,
      category_name: "Skateboarding",
      is_stock: true,
      rating: 4.4,
      reviews: 789,
      description: "The Vans Slip-On is an easy-to-wear shoe with a laid-back and iconic design.",
      size: 7
    },
    {
      _id: uuid(),

      name: "Era",
      brand: "Vans",
      image:"https://images.vegnonveg.com/resized/400X328/6738/ua-style-36-decon-sf-black-palmmarshmall-63c91ca7ab46c.jpg",
      original_price: 60,
      discounted_price: 50,
      category_name: "Skateboarding",
      is_stock: true,
      rating: 4.2,
      reviews: 543,
      description: "The Vans Era is a low-top sneaker that offers comfort and style for everyday use.",
      size: 9
    }
  
  
];


  
